import type { IBanner } from './types'
import { presetKey } from './presets'

/** Initial banners shown until an admin edits them. Mirrors the 5 bundled assets. */
export const SEED_BANNERS: IBanner[] = [
  {
    id: 'seed-sale',
    image: presetKey('sale'),
    title: 'Большая распродажа',
    subtitle: 'Скидки до 50% на популярные блюда',
    ctaLabel: 'Смотреть акции',
    href: '/',
    badge: '−50%',
    showOverlay: true,
    isActive: true,
    position: 0,
  },
  {
    id: 'seed-cashback',
    image: presetKey('cashback'),
    title: 'Кешбэк 5%',
    subtitle: 'Возвращаем баллами с каждого заказа',
    ctaLabel: 'Оформить карту',
    href: '/account/bonuses',
    badge: 'НОВОЕ',
    showOverlay: true,
    isActive: true,
    position: 1,
  },
  {
    id: 'seed-freedelivery',
    image: presetKey('freedelivery'),
    title: 'Бесплатная доставка',
    subtitle: 'При заказе от 1 000 ₽',
    ctaLabel: 'Выбрать блюда',
    href: '/',
    badge: '',
    showOverlay: true,
    isActive: true,
    position: 2,
  },
  {
    id: 'seed-deliverytime',
    image: presetKey('deliverytime'),
    title: 'Доставка за 30 минут',
    subtitle: 'Горячая еда прямо к вашей двери',
    ctaLabel: 'Заказать',
    href: '/',
    badge: '',
    showOverlay: true,
    isActive: true,
    position: 3,
  },
  {
    id: 'seed-day',
    image: presetKey('day'),
    title: 'Блюдо дня',
    subtitle: 'Специальное предложение от шефа',
    ctaLabel: 'Попробовать',
    href: '/',
    badge: 'ХИТ',
    showOverlay: true,
    isActive: true,
    position: 4,
  },
]
